version: "3.6"

services:
    nats-1:
        image: nats:2.7.1-alpine3.15
        networks:
            nat-cluster_net:
              ipv4_address: 172.16.230.100
        command: 
            - "--debug"
            - "--cluster"
            - "nats://0.0.0.0:4245"
            - "--http_port"
            - "8222"
            - "--port" 
            - "4222"
            - "--name"
            - "nats-1"
            - "--cluster_name"
            - "JSC"
            - "--js"
        ports: 
            - "4222:4222"
            - "8222:8222"
        expose: 
            - 4222
            - 8222
            - 6222
        volumes:
            - ./jetstream-cluster/nats-1:/data
    nats-2:
        image: nats:2.7.1-alpine3.15
        networks:
            nat-cluster_net:
                ipv4_address: 172.16.230.101
        command: 
            - "--debug"
            - "--cluster" 
            - "nats://0.0.0.0:4245"
            - "--http_port"
            - "8222"
            - "--port" 
            - "4222"
            - "--routes" 
            - "nats://nats-1:4245"
            - "--name"
            - "nats-2"
            - "--cluster_name"
            - "JSC"
            - "--js"
        ports: 
            - "14222:4222"
            - "18222:8222"
        expose: 
            - 4222
            - 8222
            - 6222
        depends_on:
            - nats-1
        volumes:
            - ./jetstream-cluster/nats-2:/data
networks:
    nat-cluster_net:
        driver: bridge
        ipam:
            driver: default
            config:
            -
                subnet: 172.16.230.0/24
